trigger:
- prod

pool:
  name: 'Default'

variables:
 - group: docker-credentials
 - group: docker-image
 - name: IMAGE_TAG
   value: $(Build.BuildId) 
stages:
  - stage: DockerLogin
    displayName: Docker Login
    jobs:
      - job: DockerLogin
        steps:
          - script: |
              echo "$(DOCKER_PASSWORD)" | docker login -u "$(DOCKER_USERNAME)" --password-stdin
            displayName: 'Docker Login'

  - stage: BuildPush
    displayName: Build and Push Docker Image
    dependsOn: DockerLogin
    jobs:
      - job: DockerBuildPush
        steps:
          - script: |
              echo "Building image..."
              docker build -t $(IMAGE_NAME):$(IMAGE_TAG) .
              docker push $(IMAGE_NAME):$(IMAGE_TAG)
            displayName: 'Build and Push Image'
            
